import { Page, Locator } from '@playwright/test';

export class DashboardUI {
    readonly dashboardIcon: Locator;
    readonly welcomeMessage: Locator;
    readonly workspaceDropdown: Locator;
    readonly createWorkspaceOption: Locator;
    readonly projectDropdown: Locator;
    readonly createProjectOption: Locator;
    readonly switchButtons: Locator;
    readonly searchTrigger: Locator;
    readonly searchInput: Locator;
    readonly bodyLocator: Locator;
    readonly assignedToMeSection: Locator;
    readonly ticketRows: Locator;
    readonly firstTicket: Locator;
    readonly createProjectModal: Locator;
    readonly assignedToMeText: Locator;
    readonly viewAllButton: Locator;
    readonly visibleTableRows: Locator;
    readonly bellIcon: Locator;
    readonly notificationHeading: Locator;
    readonly notificationSettingsIcon: Locator;
    readonly notificationSettingsHeading: Locator;
    readonly profileMenuBtn: Locator;
    readonly logoutBtn: Locator;
    readonly sidebarToggleBtn: Locator;
    readonly mentionsMenu: Locator;
    readonly sortBtn: Locator;
    readonly noResultsMessage: Locator;
    readonly helpLink: Locator;
    readonly quickAddTicketBtn: Locator;
    readonly ticketModalHeading: Locator;
    readonly themeToggleBtn: Locator;
    readonly liveFeedHeading: Locator;
    readonly tableColumnTicket: Locator;
    readonly tableColumnCustomer: Locator;
    readonly tableColumnStatus: Locator;
    readonly tableColumnPriority: Locator;
    readonly tableColumnDueDate: Locator;
    readonly tableColumnType: Locator;
    readonly projectCards: Locator;
    readonly activeProjectBadge: Locator;
    readonly moreOptionsBtn: Locator;
    readonly notificationCloseBtn: Locator;
    readonly workspaceOptions: Locator;
    readonly assignedToMeHeading: Locator;
    readonly viewAllBtn: Locator;
    readonly bubllyLogo: Locator;
    readonly createProjectNameInput: Locator;
    readonly createProjectSubmitBtn: Locator;
    readonly createProjectCancelBtn: Locator;
    readonly createWorkspaceNameInput: Locator;
    readonly createWorkspaceSubmitBtn: Locator;

    constructor(page: Page) {
        this.dashboardIcon = page.locator("(//div[contains(@class,'relative p-2')]//*[name()='svg'])[1]");
        this.welcomeMessage = page.locator("h1:has-text('Welcome Back')");
        this.workspaceDropdown = page.getByRole('combobox').first();
        this.createWorkspaceOption = page.getByRole('option', { name: /create new workspace/i });
        this.projectDropdown = page.locator("button.bg-primary-yellow-25").first();
        this.createProjectOption = page.getByText("Create Project");
        this.switchButtons = page.getByText('Switch');
        this.searchTrigger = page.locator("(//div[contains(@class,'rounded-xl') and contains(@class,'cursor-pointer')])[1]");
        this.searchInput = page.locator('input[placeholder="Search here..."]');
        this.bodyLocator = page.locator("body");
        this.assignedToMeSection = page.getByText("Assigned To Me");
        this.ticketRows = page.locator("table tbody tr");
        this.firstTicket = page.locator("text=#TESAFD").first();
        this.createProjectModal = page.getByText("Create Project");
        this.assignedToMeText = page.locator("text=Assigned To Me");
        this.viewAllButton = page.getByText("View All");
        this.visibleTableRows = page.locator("table:visible").last().locator("tbody tr");
        this.bellIcon = page.locator("//*[name()='svg' and contains(@class,'text-gray-text')]");
        this.notificationHeading = page.getByRole('heading', { name: 'Notifications' });
        this.notificationSettingsIcon = page.locator('h2', { hasText: 'Notifications' }).locator('..').locator('.cursor-pointer').nth(1);
        this.notificationSettingsHeading = page.getByText("Notification Settings");
        this.profileMenuBtn = page.locator('img[alt="bubllyIcon"]').last();
        this.logoutBtn = page.getByText('Logout', { exact: true });
        this.sidebarToggleBtn = page.locator('img[alt="bubllyIcon"]').first();
        this.mentionsMenu = page.locator('img[alt="bubllyIcon"]').first();
        this.sortBtn = page.locator('table thead th').first();
        this.noResultsMessage = page.getByText(/no results found|no tickets/i);
        this.helpLink = page.locator('a[href*="help"], button:has-text("Help"), button:has-text("Support")').first();
        this.quickAddTicketBtn = page.locator('table thead th').first();
        this.ticketModalHeading = page.getByRole('heading', { name: /create ticket|new ticket/i }).first();
        this.themeToggleBtn = page.locator('img[alt="bubllyIcon"]').first();
        this.liveFeedHeading = page.getByRole('heading', { name: 'Live Feed', level: 2 });
        this.tableColumnTicket = page.getByRole('columnheader', { name: '# Ticket' });
        this.tableColumnCustomer = page.getByRole('columnheader', { name: 'Customer' });
        this.tableColumnStatus = page.getByRole('columnheader', { name: 'Status' });
        this.tableColumnPriority = page.getByRole('columnheader', { name: 'Priority' });
        this.tableColumnDueDate = page.getByRole('columnheader', { name: 'Due Date' });
        this.tableColumnType = page.getByRole('columnheader', { name: 'Type' });
        this.projectCards = page.locator('h4').filter({ hasText: /Project/ });
        this.activeProjectBadge = page.getByText('Active', { exact: true });
        this.moreOptionsBtn = page.getByRole('button', { name: 'More options' }).first();
        this.notificationCloseBtn = page.locator('h2:has-text("Notifications")').locator('..').locator('.cursor-pointer').nth(2);
        this.workspaceOptions = page.locator('[role="option"]');
        this.assignedToMeHeading = page.getByRole('heading', { name: /Assigned To Me/i });
        this.viewAllBtn = page.getByRole('button', { name: 'View all' });
        this.bubllyLogo = page.locator('img[alt="bubllyIcon"]').first();
        this.createProjectNameInput = page.locator('input[placeholder="Enter Project Name"]');
        this.createProjectSubmitBtn = page.getByRole('button', { name: /^create$/i }).last();
        this.createProjectCancelBtn = page.locator('div.fixed.inset-0.z-50').locator('button:has(svg)').first();
        this.createWorkspaceNameInput = page.locator('input[placeholder="Enter workspace"]');
        this.createWorkspaceSubmitBtn = page.getByRole('button', { name: /create workspace|^create$/i }).last();
    }
}
